### ISSUE TITLE
Startet keine Clients

### ISSUE THREAD

**Issue by routerabfrage** [DxsSucuk/PrestigeLauncher#2]
Alles ist funktionstüchtig, bis auf das starten der Clients da kommt das bei raus:

java.lang.NullPointerException
	at de.presti.launcher.gui.Launcher.lambda$0(Launcher.java:100)
	at java.lang.Thread.run(Unknown Source)

Denke das es an der im client nicht vorhandenen Launcher API liegt die auch im Launcher nicht vorhanden ist.
Kann man das irgendwie fixen?

**Comment by DxsSucuk** [comment]
Du kannst ein Package namens de.prestigelauncher.api.main und da eine Methode login(String[] args) machen dann sollte es funktionieren oder die änderst den in der Klasse launcher

**Comment by routerabfrage** [comment]
Okay versuche das mal

**Comment by routerabfrage** [comment]
kannst du mir genau schicken was in die klasse soll bekomme das nicht hin

**Comment by routerabfrage** [comment]
Was soll dan in start() rein?

**Comment by routerabfrage** [comment]
bzw. dann kommt 

Loaded client data: 35697 files found
Altogether 35697 files found
Exit

Aber es startet nichts.
Finde den Fehler im Code nicht weil der Client eigentlich starten sollte.

**Comment by DxsSucuk** [comment]
Kann mich leider gerade nicht drum kümmern ich könnte morgen dir helfen sry

**Comment by routerabfrage** [comment]
Okay

**Comment by routerabfrage** [comment]
Hab das jetzt so gemacht:

In dem Client
Package "de.prestigelauncher" Erstellt
Dort eine Class mit dem Namen "LauncherAPI"
In der Klasse:
#################################################################
package de.prestigelauncher;

public class LauncherAPI {
	
	public static String login(String[] args) throws Throwable {
		return null;
		
	}
	
	public static String start(String[] args) throws Throwable {
		return null;
		
	}
}
#################################################################

Funktioniert alles aber der Client startet nicht

**Comment by DxsSucuk** [comment]
start und login sind keine Strings sondern voids sie sollen nichts returnen sonder nur einen code ausführen 

du bräuchstes das hier in start und login kannst du leer lassen 
  
  public static void start(String[] args) { Main.main(concat(new String[] { "--version", "mcp", "--accessToken", "0", "--assetsDir", "assets", "--assetIndex", "1.8", "--userProperties", "{}" }, args)); }


  
  public static <T> T[] concat(Object[] first, Object[] second) {
    Object[] arrayOfObject = Arrays.copyOf(first, first.length + second.length);
    System.arraycopy(second, 0, arrayOfObject, first.length, second.length);
    return (T[])arrayOfObject;
  }
